### ISSUE TITLE
[Feature] Create Nested PK, Identity fields

### ISSUE THREAD

**Issue by ismailsimsek** [memiiso/debezium-server-iceberg#342]
Currently consumer creates Identity fields when the fields are not nested.

- [x] Enable creating nested Identity fields done #350 #351
- [x] Enable creating Identity fields when events are not flattened #350 #351  
- [x] Add config to enable disable creating identity fields #356

**Comment by ismailsimsek** [comment]
Closed with #350 #351 #356
